finished html and css
rolandsteyn10/NFT-card pull request #1
Opened 2022-04-27 18:21 UTC by rolandsteyn10

2022-04-27 18:25 UTC, Jurgensvds requested changes

2022-04-27 18:25 UTC, Jurgensvds commented on css/main.css
> +/* Card */
Remove comment

2022-04-28 12:29 UTC, Jurgensvds requested changes

2022-04-28 12:29 UTC, Jurgensvds commented on index.html
> +    <div class="line">
Unnecessary element. Only the "card" div is required. Remove "line" div and move related styles to the "card" div

2022-04-28 12:29 UTC, Jurgensvds commented on index.html
> +              <img src="./images/icon-ethereum.svg" alt="icon" class="eth">
Whenever dealing with images it is a good idea to generally place them in their own containers so that it is easier to maintain their ratios.

```suggestion
<div class="icon-image-container">
              <img src="./images/icon-ethereum.svg" alt="icon" class="eth">
</div>
```

With this you can now set the container's width and height and set the image's max-width and max-height to 100%. This will force the image to maintain its ration so it doesn't look "Squashed". The css rules will look like this then:

```
.icon-image-container {
  width: 30px; /* Set to own custom width */
  height: 30px; /* Set to own custom height */
}

.icon-image-container > img {
  max-width: 100%;
  max-height: 100%;
}
```

2022-04-28 12:29 UTC, Jurgensvds commented on index.html
> +              <img src="./images/icon-clock.svg" alt="clock" class="clock">
Same as previous comment about image containers

2022-04-28 12:29 UTC, Jurgensvds commented on css/main.css
> +}
Move these style rules to .card

2022-04-28 12:29 UTC, Jurgensvds commented on css/main.css
> +  margin: 10px;
Padding would be more appropriate as you want all child elements to move inward

2022-04-28 12:29 UTC, Jurgensvds commented on css/main.css
> +  height: 500px;
Don't explicitly set the height, the content will set it's own height as it grows. At the moment the content actually overflows on the container.

2022-04-28 12:29 UTC, Jurgensvds commented on css/main.css
> +  border-top: grey solid 1px;
Nice divider!

2022-04-28 12:29 UTC, Jurgensvds commented on css/main.css
> +.card .main-image-container {
Add border-radius here and set overflow to hidden, then remove from border radius from child elements.

This will cause the parent element to have the border-radius and the overflow hidden will prevent the child elements from showing their corners beyond the parent element's container

2022-04-28 12:29 UTC, Jurgensvds commented on css/main.css
> +  border-radius: 10px;
Remove border radius with parent fix

2022-04-28 12:29 UTC, Jurgensvds commented on css/main.css
> +  border-radius: 10px;
Remove border radius with parent fix

2022-04-28 12:29 UTC, Jurgensvds commented on css/main.css
> +  margin: 15px 0;
You can remove the margin completely and just add padding-top to add some space between the elements and line

2022-04-28 12:29 UTC, Jurgensvds commented on css/main.css
> +  margin: 10px 0;
Margin not necessary, can remove

2022-04-28 19:29 UTC, rolandsteyn10 commented on css/main.css
> +  border-top: grey solid 1px;
Thanks [mic drop]

2022-04-29 09:58 UTC, merged